definitions:
  LogEntry.LogEntry:
    properties:
      message:
        type: string
      time:
        type: string
    type: object
  requests.AddLogRequest:
    properties:
      log:
        $ref: '#/definitions/LogEntry.LogEntry'
      userId:
        type: string
    type: object
  v1.response:
    properties:
      message:
        type: string
    type: object
info:
  contact: {}
paths:
  /logs/:
    get:
      consumes:
      - application/json
      description: get all user logs
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/LogEntry.LogEntry'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Get all logs
      tags:
      - logs
    post:
      consumes:
      - application/json
      description: Add log
      parameters:
      - description: log
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/requests.AddLogRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: integer
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Add Log
      tags:
      - logs
  /logs/{id}:
    delete:
      consumes:
      - application/json
      description: remove all user logs
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Remove All User Logs
      tags:
      - logs
  /logs/{id}{logId}:
    get:
      consumes:
      - application/json
      description: get logs by userId
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/LogEntry.LogEntry'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.response'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/v1.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/v1.response'
        default:
          description: ""
          schema:
            $ref: '#/definitions/v1.response'
      summary: Get Logs By UserId
      tags:
      - logs
swagger: "2.0"
